import turtle

turtle.begin_fill()
turtle.color('black')
turtle.forward(250)
turtle.right(90)
turtle.forward(250)
turtle.right(90)
turtle.forward(500)
turtle.right(90)
turtle.forward(500)
turtle.right(90)
turtle.forward(500)
turtle.right(90)
turtle.forward(250)
turtle.right(90)
turtle.forward(375)
turtle.end_fill()

turtle.begin_fill()
turtle.color('red')
turtle.right(90)
turtle.forward(150)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(300)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(300)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()

turtle.begin_fill()
turtle.color('black')
turtle.forward(225)
turtle.right(90)
turtle.end_fill()

turtle.begin_fill()
turtle.color('red')
turtle.forward(300)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(300)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(300)
turtle.right(143)
turtle.end_fill()

turtle.begin_fill()
turtle.color('red')
turtle.forward(373)
turtle.left(49)
turtle.forward(50)
turtle.left(130)
turtle.forward(373)
turtle.end_fill()
turtle.done()